-- MySQL Script generated by MySQL Workbench
-- Mon Aug  6 11:18:31 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema engloba
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema engloba
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `engloba` DEFAULT CHARACTER SET utf8 ;
USE `engloba` ;

-- -----------------------------------------------------
-- Table `engloba`.`modulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `engloba`.`modulos` (
  `id_modulo` INT NOT NULL AUTO_INCREMENT,
  `curso` VARCHAR(45) NULL,
  `tamanho` VARCHAR(45) NULL,
  `documentos` VARCHAR(45) NULL,
  PRIMARY KEY (`id_modulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `engloba`.`instituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `engloba`.`instituicao` (
  `id_institu` INT NOT NULL AUTO_INCREMENT,
  `nome_institu` VARCHAR(45) NOT NULL,
  `endereco_institu` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `modulos` INT NOT NULL,
  `valor` VARCHAR(45) NULL,
  PRIMARY KEY (`id_institu`),
  INDEX `modulos_idx` (`modulos` ASC),
  CONSTRAINT `modulos`
    FOREIGN KEY (`modulos`)
    REFERENCES `engloba`.`modulos` (`id_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `engloba`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `engloba`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nivel` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NULL,
  `data_nasc` VARCHAR(45) NULL,
  `instituicao` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `instituicao_idx` (`instituicao` ASC),
  CONSTRAINT `instituicao`
    FOREIGN KEY (`instituicao`)
    REFERENCES `engloba`.`instituicao` (`id_institu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `engloba`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `engloba`.`cursos` (
  `id_curso` INT NOT NULL,
  `nome_curso` VARCHAR(45) NULL,
  `duracao` VARCHAR(45) NULL,
  `instituicao` INT NOT NULL,
  PRIMARY KEY (`id_curso`),
  INDEX `instituicao_idx` (`instituicao` ASC),
  CONSTRAINT `instituicao`
    FOREIGN KEY (`instituicao`)
    REFERENCES `engloba`.`instituicao` (`id_institu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `engloba`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `engloba`.`aluno` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `cpf` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `matricula` VARCHAR(45) NULL,
  `curso` INT NULL,
  PRIMARY KEY (`id_aluno`),
  INDEX `curso_idx` (`curso` ASC),
  INDEX `id_usuario_idx` (`id_usuario` ASC),
  CONSTRAINT `curso`
    FOREIGN KEY (`curso`)
    REFERENCES `engloba`.`cursos` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `engloba`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `engloba`.`funcionario_engloba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `engloba`.`funcionario_engloba` (
  `id_funcionario_engloba` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `endereco` VARCHAR(45) NULL,
  PRIMARY KEY (`id_funcionario_engloba`),
  INDEX `id_usuario_idx` (`id_usuario` ASC),
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `engloba`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `engloba`.`funcionario_escola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `engloba`.`funcionario_escola` (
  `id_funcionario_escola` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `cargo` INT NOT NULL,
  PRIMARY KEY (`id_funcionario_escola`),
  INDEX `id_usuario_idx` (`id_usuario` ASC),
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `engloba`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `engloba`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `engloba`.`disciplina` (
  `id_disciplina` INT NOT NULL AUTO_INCREMENT,
  `nome_disc` VARCHAR(45) NULL,
  `carga_horaria` VARCHAR(45) NULL,
  `professor` INT NOT NULL,
  `curso` INT NULL,
  `instituicao` INT NOT NULL,
  PRIMARY KEY (`id_disciplina`),
  INDEX `instituicao_idx` (`instituicao` ASC),
  INDEX `professor_idx` (`professor` ASC),
  INDEX `curso_idx` (`curso` ASC),
  CONSTRAINT `instituicao`
    FOREIGN KEY (`instituicao`)
    REFERENCES `engloba`.`instituicao` (`id_institu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `professor`
    FOREIGN KEY (`professor`)
    REFERENCES `engloba`.`funcionario_escola` (`id_funcionario_escola`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `curso`
    FOREIGN KEY (`curso`)
    REFERENCES `engloba`.`cursos` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `engloba`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `engloba`.`turma` (
  `id_turma` INT NOT NULL,
  `nome_turma` VARCHAR(45) NOT NULL,
  `curso` INT NULL,
  `ano` VARCHAR(45) NULL,
  `instituicao` INT NOT NULL,
  PRIMARY KEY (`id_turma`),
  INDEX `curso_idx` (`curso` ASC),
  INDEX `instituicao_idx` (`instituicao` ASC),
  CONSTRAINT `curso`
    FOREIGN KEY (`curso`)
    REFERENCES `engloba`.`cursos` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `instituicao`
    FOREIGN KEY (`instituicao`)
    REFERENCES `engloba`.`instituicao` (`id_institu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `engloba`.`alunos_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `engloba`.`alunos_turma` (
  `id_alunos_turma` INT NOT NULL,
  `id_aluno` INT NOT NULL,
  `id_turma` INT NOT NULL,
  `instituicao` INT NOT NULL,
  PRIMARY KEY (`id_alunos_turma`),
  INDEX `id_aluno_idx` (`id_aluno` ASC),
  INDEX `id_turma_idx` (`id_turma` ASC),
  INDEX `instituicao_idx` (`instituicao` ASC),
  CONSTRAINT `id_aluno`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `engloba`.`aluno` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_turma`
    FOREIGN KEY (`id_turma`)
    REFERENCES `engloba`.`turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `instituicao`
    FOREIGN KEY (`instituicao`)
    REFERENCES `engloba`.`instituicao` (`id_institu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- CREATE TABLE `eventos` (
--   `id` int(11) NOT NULL,
--   `title` varchar(220) DEFAULT NULL,
--   `color` varchar(10) DEFAULT NULL,
--   `start` datetime DEFAULT NULL,
--   `end` datetime DEFAULT NULL
-- ) ENGINE=MyISAM DEFAULT CHARSET=utf8;
-- 
-- ALTER TABLE `eventos`
--   ADD PRIMARY KEY (`id`);
-- 
-- ALTER TABLE `eventos`
--   MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;
